### PR TITLE
Static content caching header fix

### LINKED ISSUE #2529: StaticFile.fromFile ignores modified ETag if unmodified since
StaticFile.fromFile will return early with a 302 if the resource has not modified since, ignoring the request ETag. If the ETag provided in the If-None-Match header is different from that of the resource, a 302 should not be returned, regardless of the not modified since check.

As far as I understand from the spec, both conditions need to be checked before returning a 302:

> If both an entity tag and a Last-Modified value have been
>         provided by the origin server, SHOULD use both validators in
>         cache-conditional requests.

This makes more sense if you consider rolling back a file to an older version, where the modification date is taken as when the version was authored, rather than when it was rolled back. Maybe this is unusual, although the above suggests it's covered in the spec and I just encountered it in the wild.

### PR DESCRIPTION
**Pull request by rhyskeepence**
Fixes #2529

### CODE REVIEW

File: core/src/main/scala/org/http4s/StaticFile.scala [hunk 1]
```diff
@@ -1,18 +1,21 @@
 package org.http4s
 
+import java.io._
+import java.net.URL
+
+import cats.Semigroup
 import cats.data._
 import cats.effect._
-import cats.implicits.{catsSyntaxEither => _, _}
+import cats.implicits._
```
Comment (rossabaker) [inline core/src/main/scala/org/http4s/StaticFile.scala]: That catsSyntaxEither trick actually is necessary with the strict compiler flags and 2.11 support.

Comment (rhyskeepence) [reply core/src/main/scala/org/http4s/StaticFile.scala]: Got it, thanks!

File: core/src/main/scala/org/http4s/StaticFile.scala [hunk 2]
```diff
@@ -1,18 +1,21 @@
 package org.http4s
 
+import java.io._
+import java.net.URL
+
+import cats.Semigroup
```
Comment (aeons) [inline core/src/main/scala/org/http4s/StaticFile.scala]: We generally have all imports in the same list, ordered alphabetically.

Comment (rossabaker) [reply core/src/main/scala/org/http4s/StaticFile.scala]: We ended up removing the IntelliJ setting that did this for people, right?  It's a pity that scalafmt can't just do this for people.

**Comment by rossabaker** [comment]
I don't immediately recognize that lingering Scala 2.11 failure.  The other build failure is a blaze flake and not your fault.

File: core/src/main/scala/org/http4s/StaticFile.scala [hunk 3]
```diff
@@ -163,25 +160,37 @@ object StaticFile {
...
     } yield res)
 
-  private def ifETagModified[F[_]](req: Option[Request[F]], etagCalc: ETag) =
+  private def notModified[F[_]](
+      req: Option[Request[F]],
+      etagCalc: ETag,
+      lastModified: Option[HttpDate]): Option[Response[F]] = {
+
+    implicit val conjunction: Semigroup[Boolean] =
+      (x: Boolean, y: Boolean) => x && y
```
Comment (rossabaker) [inline core/src/main/scala/org/http4s/StaticFile.scala]: This works starting in Scala 2.12 because of the single abstract method thingy, but it fails to compile in 2.12.  I think it just needs the whole `new Semigroup { ... }` ceremony.

File: server/src/main/scala/org/http4s/server/middleware/Metrics.scala [hunk 4]
```diff
@@ -39,7 +39,7 @@ object Metrics {
       classifierF: Request[F] => Option[String] = { _: Request[F] =>
         None
       }
-  )(routes: HttpRoutes[F])(implicit F: Effect[F], clock: Clock[F]): HttpRoutes[F] =
+  )(routes: HttpRoutes[F])(implicit F: Sync[F], clock: Clock[F]): HttpRoutes[F] =
```
Comment (rossabaker) [inline server/src/main/scala/org/http4s/server/middleware/Metrics.scala]: This will break MiMa.  I think it got picked up when you changed branches.

File: tests/src/test/scala/org/http4s/StaticFileSpec.scala [hunk 5]
```diff
@@ -66,6 +86,21 @@ class StaticFileSpec extends Http4sSpec {
       response.map(_.status) must beSome(NotModified)
     }
 
+    "Send modified files when either the ETag or last modified date do not match" in {
```
Comment (rossabaker) [inline tests/src/test/scala/org/http4s/StaticFileSpec.scala]: Isn't this testing when the Etag doesn't match, and it's not tested when the If-Modified-Since doesn't match?  The "either" implies two tests to me.

File: core/src/main/scala/org/http4s/StaticFile.scala (hunk 2 above)
Comment (rhyskeepence) [reply core/src/main/scala/org/http4s/StaticFile.scala]: Yeah, sorry, I was using the default IntelliJ settings. This should be resolved now!

File: tests/src/test/scala/org/http4s/StaticFileSpec.scala (hunk 5 above)
Comment (rhyskeepence) [reply tests/src/test/scala/org/http4s/StaticFileSpec.scala]: Yes, you're correct, there should be two tests.

File: server/src/main/scala/org/http4s/server/middleware/Metrics.scala (hunk 4 above)
Comment (rhyskeepence) [reply server/src/main/scala/org/http4s/server/middleware/Metrics.scala]: What's the best way to resolve this? Change the target branch of this PR to master, or create a new PR with the correct source branch?

**Comment by rossabaker** [comment]
We're going to have to rebase to get the two commits that aren't @rhyskeepence's off this PR, but it looks good to me after that.

File: server/src/main/scala/org/http4s/server/middleware/Metrics.scala (hunk 4 above)
Comment (rossabaker) [reply server/src/main/scala/org/http4s/server/middleware/Metrics.scala]: Target master won't get it into the 0.20 series.  Which we're about to release, but since you're still awake, we'll squeeze this in.

You can `git rebase -i` against series/0.20 and drop the two commits that aren't yours and force push, or you can open a new PR.  Whatever's easier for you.

Comment (rhyskeepence) [reply server/src/main/scala/org/http4s/server/middleware/Metrics.scala]: Thank you, I have rebased and force pushed.
