### PR TITLE
Drain response body in `DefaultClient#defaultOnError`

### LINKED ISSUE #3707: Improve Logging On Failed Expect
https://github.com/http4s/http4s/blob/master/client/src/main/scala/org/http4s/client/DefaultClient.scala#L228

This default response does not actually compile the stream or observe the failed bodies so they do not appear in loggers. The fix is as easy as changing constraint to sync on this method and then calling 

`resp.body.compile.drain.as(UnexpectedStatus(resp.status))`

### PR DESCRIPTION
**Pull request by danicheg**
This fixes #3707.
Credit to @ChristopherDavenport and @rossabaker for their work/discussion in #3708.

### CODE REVIEW

**Comment by armanbilge** [comment]
> Unfortunately, the same fix couldn't be applied for ember-client, because it has a weaker `MonadCancelThrow` constraint.

Can we pattern match on the constraint, to see if it is in fact `Concurrent` and then do the right thing in that case? This is an idea that started in Cats Effect, e.g. see https://github.com/typelevel/cats-effect/issues/2772

File: blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClient.scala [hunk 1]
```diff
@@ -95,6 +97,11 @@ private class BlazeClient[F[_], A <: BlazeConnection[F]](
     } yield response
   }
 
+  override def defaultOnError(req: Request[F])(resp: Response[F])(implicit
+      G: Applicative[F]
+  ): F[Throwable] =
+    resp.body.compile.drain.as(UnexpectedStatus(resp.status, req.method, req.uri))
```
Comment (danicheg) [inline blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClient.scala:103]: Reminder: in `main` this should be like
```scala
  override def defaultOnError(req: Request[F])(resp: Response[F])(implicit
      G: Applicative[F]
  ): F[Throwable] =
    resp.entity match {
      case Entity.Empty | Entity.Strict(_) =>
        F.pure(UnexpectedStatus(resp.status, req.method, req.uri))
      case Entity.Default(body, _) =>
        body.compile.drain.as(UnexpectedStatus(resp.status, req.method, req.uri))
    }
```

**Comment by danicheg** [comment]
@armanbilge oh, indeed, thanks. Though I don't that much like this approach, however it works and uses many times in Typelevel libraries.

**Comment by danicheg** [comment]
Pushing this pattern forward, we could apply it even in `DefaultClient` and have one version for every client. Though this pattern is kinda tricky. So maybe it'd be better to use it in particular implementations, not interfaces. I dunno, left it as-is for comments.

File: ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClient.scala [hunk 2]
```diff
@@ -36,4 +38,15 @@ final class EmberClient[F[_]] private[client] (
...
+
+  override def defaultOnError(req: Request[F])(resp: Response[F])(implicit
+      G: Applicative[F]
+  ): F[Throwable] = F match {
+    case concurrentF: Concurrent[F @unchecked] =>
+      implicit val C = concurrentF
+      resp.body.compile.drain.as(UnexpectedStatus(resp.status, req.method, req.uri))
+
+    case _ =>
+      F.pure(UnexpectedStatus(resp.status, req.method, req.uri))
```
Comment (rossabaker) [inline ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClient.scala:50]: Is this case worth logging a warning that the behavior is buggy?

Comment (danicheg) [reply ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClient.scala:50]: Basically, I believe this case shouldn't appear at runtime, because 99% of effect usage is CE.IO/monix.Task/etc effect that is supposed to have a `Concurrent` instance. But `defaultOnError` is used for serving requests overall, and end-users could even don't use logging, but this method actually will be used. So this case preserves the current behavior of request processing mostly, not just logging behavior.

**Review by rossabaker — APPROVED** [review]
Yeah, it should improve things in most practice, and isn't worse anywhere.

**Comment by danicheg** [comment]
@armanbilge Is your point strict for merging? Don't you mind if we go ahead with this as is?

**Review by armanbilge — APPROVED** [review]
I agree with Ross, the only "strict" here is strictly improving :)
