### PR TITLE
Fixes #7283: make BasicCredentials constructor safe

### LINKED ISSUE #7283: Bug: deserializing malformed basic auth token results in java.lang.IllegalArgumentException raised outside of F
The exception is being raised when calling `BasicCredentials.unapply` method in pattern matching statement at https://github.com/http4s/http4s/blob/series/0.23/server/shared/src/main/scala/org/http4s/server/middleware/authentication/BasicAuth.scala#L69

It causes the situation when you need to catch an exception using try/catch instead of leveraging cats-effect machinery.
```
java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at 132
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:774)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:538)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:561)
	at org.http4s.BasicCredentials$.apply(Credentials.scala:106)
	at org.http4s.BasicCredentials$.unapply(Credentials.scala:118)
	at org.http4s.server.middleware.authentication.BasicAuth$.validatePassword(BasicAuth.scala:69)
	at org.http4s.server.middleware.authentication.BasicAuth$.$anonfun$challenge$1(BasicAuth.scala:57)
```

I think it should be considered a bug.

### PR DESCRIPTION
**Pull request by grouzen**
This PR provides a fix for #7283 by replacing the existing `BasicCredentials.apply` constructor with `BasicCredentials.fromString` and using it in `BasicCredentials.unapply` to make pattern matching safe too.

### CODE REVIEW

**Review by hamnis — APPROVED** [review]

**Review by nylonee — APPROVED** [review]

File: core/shared/src/main/scala/org/http4s/Credentials.scala [hunk 1]
```diff
@@ -102,6 +102,7 @@ object BasicCredentials {
   private def decode(bytes: Array[Byte], charset: JavaCharset): String =
     new String(bytes, charset)
 
+  @deprecated("Use fromString instead", "0.23.24")
   def apply(token: String): BasicCredentials = {
     val bytes = Base64.getDecoder.decode(token)
```
Comment (armanbilge) [inline core/shared/src/main/scala/org/http4s/Credentials.scala:107]: Can we de-duplicate this code by calling `fromString(...).get`?

File: core/shared/src/main/scala/org/http4s/Credentials.scala [hunk 2]
```diff
@@ -102,21 +102,26 @@ object BasicCredentials {
...
-  def apply(token: String): BasicCredentials = {
-    val bytes = Base64.getDecoder.decode(token)
-    val (userPass, charset) = decode(bytes, utf8CharsetDecoder)
-      .fold(_ => (decode(bytes, fallbackCharset), fallbackCharset), up => (up, utf8Charset))
-    userPass.indexOf(':') match {
-      case -1 => apply(userPass, "", charset)
-      case ix => apply(userPass.substring(0, ix), userPass.substring(ix + 1), charset)
+  @deprecated("Use fromString instead", "0.23.24")
+  def apply(token: String): BasicCredentials =
+    fromString(token).get
```
Comment (danicheg) [inline core/shared/src/main/scala/org/http4s/Credentials.scala:107]: If I'm not wrong, previously there was an `IllegalArgumentException`, and now it will be `NoSuchElementException`. Although the difference is subtle, shouldn't we preserve the behaviour?

Comment (grouzen) [reply core/shared/src/main/scala/org/http4s/Credentials.scala:107]: Good point!

Comment (grouzen) [reply core/shared/src/main/scala/org/http4s/Credentials.scala]: Fixed this one.

File: core/shared/src/main/scala/org/http4s/Credentials.scala [hunk 3]
```diff
@@ -102,21 +102,29 @@ object BasicCredentials {
...
     new String(bytes, charset)
 
-  def apply(token: String): BasicCredentials = {
-    val bytes = Base64.getDecoder.decode(token)
-    val (userPass, charset) = decode(bytes, utf8CharsetDecoder)
-      .fold(_ => (decode(bytes, fallbackCharset), fallbackCharset), up => (up, utf8Charset))
-    userPass.indexOf(':') match {
-      case -1 => apply(userPass, "", charset)
-      case ix => apply(userPass.substring(0, ix), userPass.substring(ix + 1), charset)
+  private def fromString0(token: String): Try[BasicCredentials] =
```
[the remark this answers is not in the document]
Comment (armanbilge) [reply core/shared/src/main/scala/org/http4s/Credentials.scala:105]: Personally I use `Impl` but it's just a private method, I don't really care :)

```suggestion
  private def fromStringImpl(token: String): Try[BasicCredentials] =
```

**Review by armanbilge — APPROVED** [review]
Thanks for iterating!

**Review by danicheg — APPROVED** [review]
