### PR TITLE
Distinguish between reserved and unknown frame opcodes

### LINKED ISSUE #2606: WebSocket server doesn't properly handle protocol mistakes.
Unfortunately, I don't know how exactly to reproduce this error.

The problem is that when I ran a local WebSocket server it was closing all incoming connections and printing the next stack trace:
```
scala.MatchError: 7 (of class java.lang.Integer)
    at org.http4s.websocket.package$.makeFrame(package.scala:26)
    at org.http4s.websocket.FrameTranscoder.bufferToFrame(FrameTranscoder.scala:165)
    at org.http4s.server.blaze.WebSocketDecoder.bufferToMessage(WebSocketDecoder.scala:30)
    at org.http4s.blaze.pipeline.stages.ByteToObjectStage.$anonfun$readAndDecodeLoop$1(ByteToObjectStage.scala:85)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
    at org.http4s.blaze.util.Execution$ThreadLocalTrampoline.run(Execution.scala:108)
    at org.http4s.blaze.util.Execution$ThreadLocalTrampoline.execute(Execution.scala:94)
    at org.http4s.blaze.util.Execution$$anon$2.execute(Execution.scala:53)
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
    at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallback(Promise.scala:312)
    at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:303)
    at org.http4s.blaze.pipeline.stages.ByteToObjectStage.readAndDecodeLoop(ByteToObjectStage.scala:99)
    at org.http4s.blaze.pipeline.stages.ByteToObjectStage.startReadDecode(ByteToObjectStage.scala:72)
    at org.http4s.blaze.pipeline.stages.ByteToObjectStage.readRequest(ByteToObjectStage.scala:68)
    at org.http4s.blaze.pipeline.stages.ByteToObjectStage.readRequest$(ByteToObjectStage.scala:56)
    at org.http4s.server.blaze.WebSocketDecoder.readRequest(WebSocketDecoder.scala:8)
    at org.http4s.blaze.pipeline.Tail.channelRead(Stages.scala:88)
    at org.http4s.blaze.pipeline.Tail.channelRead$(Stages.scala:85)
    at org.http4s.server.blaze.WSFrameAggregator.channelRead(WSFrameAggregator.scala:16)
    at org.http4s.server.blaze.WSFrameAggregator.readRequest(WSFrameAggregator.scala:24)
    at org.http4s.blaze.pipeline.Tail.channelRead(Stages.scala:88)
    at org.http4s.blaze.pipeline.Tail.channelRead$(Stages.scala:85)
    at org.http4s.blazecore.websocket.Http4sWSStage.channelRead(Http4sWSStage.scala:18)
    at org.http4s.blazecore.websocket.Http4sWSStage.$anonfun$readFrameTrampoline$1(Http4sWSStage.scala:54)
    at org.http4s.blazecore.websocket.Http4sWSStage.$anonfun$readFrameTrampoline$1$adapted(Http4sWSStage.scala:53)
    at monix.eval.internal.TaskCreate$.$anonfun$async$1(TaskCreate.scala:124)
    at monix.eval.internal.TaskCreate$.$anonfun$async$1$adapted(TaskCreate.scala:121)
    at monix.eval.internal.TaskRestartCallback.start(TaskRestartCallback.scala:58)
    at monix.eval.internal.TaskRunLoop$.executeAsyncTask(TaskRunLoop.scala:564)
    at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:115)
    at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:192)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Seems that it doesn't properly handle deviations from the protocol and throws an error in case if a received opcode doesn't match to the expected valid set of opcodes.

I've checked the WebSockets RFC and it says that a server must close a connection and return 400 in case of an handshake error - https://tools.ietf.org/html/rfc6455#section-4.2.1

Also, it says that opcodes from 3 to 7 are reserved for the future usage and I didn't find information on how they should be handled exactly. However, there is a sentence: `If an unknown
      opcode is received, the receiving endpoint MUST _Fail the
      WebSocket Connection_.`, though not sure if it's applicable to them - https://tools.ietf.org/html/rfc6455#section-5.2

Probably at least server could handle such opcodes and print something less scary and more understandable for users.

### PR DESCRIPTION
**Pull request by vasilmkd**
Resolves #2606.

Opening as a draft because I would like an initial review and some pointers on how (or if) to test this. I've only made changes to `core` and `blaze-server`. Do any of the other backends need adjusting?

### CODE REVIEW

File: blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala [hunk 1]
```diff
@@ -99,19 +100,24 @@ private[http4s] class Http4sWSStage[F[_]](
...
-        } yield c
-      case p @ Ping(d) =>
-        //Reply to ping frame immediately
-        writeFrame(Pong(d), trampoline) >> F.pure(p)
-      case rest =>
-        F.pure(rest)
-    }
+    readFrameTrampoline
+      .recoverWith {
+        case _: ReservedOpcodeException => F.delay(Close(1003)).flatMap(F.fromEither)
```
Comment (vasilmkd) [inline blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala:105]: Not sure if this can be `F.fromEither(Close(1003))` directly?

File: blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketDecoder.scala [hunk 2]
```diff
@@ -42,5 +43,6 @@ private class WebSocketDecoder
     * @return optional message if enough data was available
     */
   @throws[TranscodeError]
+  @throws[ProtocolException]
   def bufferToMessage(in: ByteBuffer): Option[WebSocketFrame] = Option(bufferToFrame(in))
```
Comment (vasilmkd) [inline blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketDecoder.scala:47]: I'm interested, why is this wrapped in an Option?

File: blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala (hunk 1 above)
Comment (rossabaker) [reply blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala:105]: Yeah, there's no side effect here, right?

File: blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketDecoder.scala (hunk 2 above)
Comment (rossabaker) [reply blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketDecoder.scala:47]: It can null, which is Evil.  The `Option` is introduced in the wrong place, I think.

File: blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala (hunk 1 above)
Comment (vasilmkd) [reply blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala:105]: Judging by the `apply` method, I think so.

File: blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketDecoder.scala (hunk 2 above)
Comment (vasilmkd) [reply blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketDecoder.scala:47]: Does your comment mandate any changes?

File: core/src/main/scala/org/http4s/websocket/package.scala [hunk 3]
```diff
@@ -38,20 +39,28 @@ package object websocket {
...
+        if (!last) throw new ProtocolException("Control frame cannot be fragmented: Ping")
+        else WebSocketFrame.Ping(data)
+      case 0xa =>
+        if (!last) throw new ProtocolException("Control frame cannot be fragmented: Pong")
+        else WebSocketFrame.Pong(data)
+      case 0xb | 0xc | 0xd | 0xe | 0xf =>
+        // Reserved for future control frames.
+        throw new ReservedOpcodeException(opcode)
+      case _ =>
+        throw new ProtocolException(s"Unknown frame opcode: $opcode")
```
[the remark this answers is not in the document]
Comment (vasilmkd) [reply core/src/main/scala/org/http4s/websocket/package.scala:64]: I can certainly do that.

File: blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketDecoder.scala (hunk 2 above)
Comment (rossabaker) [reply blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketDecoder.scala:47]: No, I think it's the right thing for the issue at hand.  But that function that can return `null` should be refactored to not as separate work.

File: blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala (hunk 1 above)
Comment (vasilmkd) [reply blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala]: Done.

File: core/src/main/scala/org/http4s/websocket/package.scala (hunk 3 above)
[the remark this answers is not in the document]
Comment (vasilmkd) [reply core/src/main/scala/org/http4s/websocket/package.scala]: Done.

**Review by rossabaker — APPROVED** [review]
