### PR TITLE
Encode URI path segments created with `/`

### LINKED ISSUE #705: '/' allows creation of invalid URIs
We're very safe until we're not.

```scala
scala> Uri.uri("http://www.example.com/ foo")
<console>:9: error: '/', 'EOI', '#', '?' or Segment
              Uri.uri("http://www.example.com/ foo")
                     ^
scala> Uri.uri("http://www.example.com") / " foo"
res4: org.http4s.Uri = http://www.example.com/ foo

scala> Uri.fromString(res4.toString)
res5: org.http4s.ParseResult[org.http4s.Uri] = -\/(org.http4s.ParseFailure: '/', 'EOI', '#', '?' or Segment)
```

### PR DESCRIPTION
**Pull request by rossabaker**
Fixes #705

### CODE REVIEW

File: dsl/src/main/scala/org/http4s/dsl/Path.scala [hunk 1]
```diff
@@ -93,7 +93,7 @@ object ~ {
 final case class /(parent: Path, child: String) extends Path {
   lazy val toList: List[String] = parent.toList ++ List(child)
   def lastOption: Option[String] = Some(child)
-  lazy val asString = parent.toString + "/" + UrlCodingUtils.urlEncode(child, toSkip = Path.pathUnreserved)
+  lazy val asString = s"${parent}/${Uri.pathEncode(child, Charset.`UTF-8`)}"
```
Comment (rossabaker) [inline dsl/src/main/scala/org/http4s/dsl/Path.scala]: Maybe this case class needs a charset?  Would have to be an implicit parameter to the constructor, I think.

It was hardcoded UTF-8 before, and nobody complained.

File: core/src/main/scala/org/http4s/Uri.scala [hunk 2]
```diff
@@ -29,10 +29,15 @@ final case class Uri(
   fragment: Option[Fragment] = None)
   extends QueryOps with Renderable
 {
+  import Uri._
+
   def withPath(path: Path): Uri = copy(path = path)
 
-  def /(newFragment: Path): Uri = {
-    val newPath = if (path.isEmpty || path.last != '/') path + "/" + newFragment else path + newFragment
+  def /(newSegment: Path)(implicit charset: Charset = Charset.`UTF-8`): Uri = {
```
Comment (ceedubs) [inline core/src/main/scala/org/http4s/Uri.scala]: Is there any case in which it makes sense to have different segments encoded with different charsets? I suspect not, which makes me wonder if the `charset` should be part of the class as opposed to an argument to this method. But then it also seems like you shouldn't need a charset for an empty path, and I guess it's probably safe to assume that people will use the same charset throughout construction of their URL.

I think there's another option which is more breaking but possibly more elegant. What if `path` were something like `List[Segment]`? Then you could have a couple options. You could just have `type Segment = String` and require a charset when you try to render the path as a string. Or you could have something like:

```scala
final class Segment private(val encoded: String) extends AnyVal

object Segment {
  /** Encodes the string with the provided charset */
  def apply(s: String)(implicit charset: Charset = Charset.`UTF-8`): Segment = ...

  /** Create a segment without encoding it. This is useful if your segment is already encoded or you know that it doesn't need to be (because it is an `Int`, `Long`, `Boolean`, etc. */
  def noEncoding(s: String): Segment = new Segment(s)
}
```

You could even go a step further and create a type class for types that can be encoded for path segments and then you could have something like:

```scala
def /[A](a: A)(implicit pathEncoder: PathEncoder[A]): Uri = ...
```

And then people could pass in a `String`, a `Long`, etc in path segments and we (the type class instances) could be smart enough to know that if it's a `String` we should encode it, but if it's a `Long` we can just call `toString`.

This is just a stream of consciousness. Feel free to completely disregard all of it.

Comment (rossabaker) [inline core/src/main/scala/org/http4s/Uri.scala]: I can't think of it ever making sense to change charsets while constructing a URI.  Making it a property of the URI is possible, but there are a lot of URIs, and 99.9999% of them are UTF-8 and the other 0.0001% are bad and should feel bad.

A richer data type would allow deferring the encoding to a time that one charset is passed in.  The smarter data type is proposed at #559

Comment (rossabaker) [inline core/src/main/scala/org/http4s/Uri.scala]: It turns out we're already heavily biased toward UTF-8: the query and fragment rendering of the Uri assume this.

Comment (bryce-anderson) [inline core/src/main/scala/org/http4s/Uri.scala]: I don't think it makes sense to assume a charset in one section and make the other configurable (even with a default).

File: core/src/main/scala/org/http4s/util/UrlCoding.scala [hunk 3]
```diff
@@ -4,65 +4,69 @@
...
-    if (needsUrlEncoding(string)) urlEncode(string) else string
+  private val toSkip =
+    Unreserved ++ "!$&'()*+,;=:/?@"
 
-  def ensureUppercasedEncodings(string: String): String =
-    LowerPctEncoded.replaceAllIn(string, (_: Match) match {
-      case Regex.Groups(v) => "%" + v.toUpperCase(Locale.ENGLISH)
-    })
+  // scalastyle:off magic.number
+  private val HexUpperCaseChars = (0 until 16) map { i ⇒ Character.toUpperCase(Character.forDigit(i, 16)) }
```
Comment (bryce-anderson) [inline core/src/main/scala/org/http4s/util/UrlCoding.scala]: Any chance you'd be interested in changing this `⇒` to a `=>`?

File: core/src/test/scala/org/http4s/UriSpec.scala [hunk 4]
```diff
@@ -697,4 +697,36 @@ class UriSpec extends Http4sSpec with MustThrownMatchers {
...
+      uri("http://example.com/") / "ö" must_== uri("http://example.com/%C3%B6")
+    }
+
+    "encode according to charset" in {
+      implicit val cs = Charset.`ISO-8859-1`
+      uri("http://example.com/") / "ö" must_== uri("http://example.com/%F6")      
+    }
+
+    "not make bad URIs" >> forAll { s: String =>
+      Uri.fromString("http://example.com/").map(_ / s) must be_\/-
```
Comment (bryce-anderson) [inline core/src/test/scala/org/http4s/UriSpec.scala]: Isn't this always going to succeed because the `/` operator will _always_ succeed?

File: core/src/main/scala/org/http4s/util/UrlCoding.scala (hunk 3 above)
Comment (rossabaker) [inline core/src/main/scala/org/http4s/util/UrlCoding.scala]: I would love to!

File: core/src/test/scala/org/http4s/UriSpec.scala (hunk 4 above)
Comment (rossabaker) [inline core/src/test/scala/org/http4s/UriSpec.scala]: Oops. The intent was to ensure that the result still parses.  Good catch.

File: core/src/main/scala/org/http4s/Uri.scala (hunk 2 above)
Comment (rossabaker) [inline core/src/main/scala/org/http4s/Uri.scala]: I think storing decoded segments instead of a String makes the most sense.

**Comment by rossabaker** [comment]
I think it's possible that a smarter path structure would make routing more efficient.  I think it should be made possible to encode URIs to other charsets, though nobody has ever asked for it.  But I think this leaves us in a better place than we were.
