### PR TITLE
Address Uri#fromString Defect for Parsing the Port

### LINKED ISSUE #2583: Uri.fromString throws on some invalid port numbers
`org.http4s.Uri.fromString` throws when the port number is greater than 2,147,483,647  (`java.lang.Integer.MAX_VALUE`).

Versions
Present in 0.20.1 and 0.18.23

```scala
$ amm
Loading...
Welcome to the Ammonite Repl 1.1.2
(Scala 2.12.6 Java 1.8.0_181)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import $ivy.`org.http4s::http4s-core:0.18.23`
import $ivy.$

@ org.http4s.Uri.fromString("https://example.com:2147483647")
res1: org.http4s.package.ParseResult[org.http4s.Uri] = Right(
  Uri(
    Some(Scheme(https)),
    Some(Authority(None, RegName(example.com), Some(2147483647))),
    "",
    Query(),
    None
  )
)

@ // Greater than java.lang.Integer.MAX_VALUE

@ org.http4s.Uri.fromString("https://example.com:2147483648")
java.lang.NumberFormatException: For input string: "2147483648"
  java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  java.lang.Integer.parseInt(Integer.java:587)
  java.lang.Integer.parseInt(Integer.java:615)
  scala.collection.immutable.StringLike.toInt(StringLike.scala:301)
  scala.collection.immutable.StringLike.toInt$(StringLike.scala:301)
  scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
  org.http4s.parser.Rfc3986Parser.Port(Rfc3986Parser.scala:85)
  org.http4s.parser.Rfc3986Parser.Port$(Rfc3986Parser.scala:83)
  org.http4s.parser.RequestUriParser.Port(RequestUriParser.scala:8)
  org.http4s.parser.Rfc3986Parser.Authority(Rfc3986Parser.scala:64)
  org.http4s.parser.Rfc3986Parser.Authority$(Rfc3986Parser.scala:63)
  org.http4s.parser.RequestUriParser.Authority(RequestUriParser.scala:8)
  org.http4s.parser.Rfc3986Parser.HierPart(Rfc3986Parser.scala:40)
  org.http4s.parser.Rfc3986Parser.HierPart$(Rfc3986Parser.scala:39)
  org.http4s.parser.RequestUriParser.HierPart(RequestUriParser.scala:8)
  org.http4s.parser.Rfc3986Parser.AbsoluteUri(Rfc3986Parser.scala:25)
  org.http4s.parser.Rfc3986Parser.AbsoluteUri$(Rfc3986Parser.scala:24)
  org.http4s.parser.RequestUriParser.AbsoluteUri(RequestUriParser.scala:8)
  org.http4s.parser.Rfc3986Parser.Uri(Rfc3986Parser.scala:22)
  org.http4s.parser.Rfc3986Parser.Uri$(Rfc3986Parser.scala:22)
  org.http4s.parser.RequestUriParser.Uri(RequestUriParser.scala:8)
  org.http4s.Uri$.$anonfun$fromString$1(Uri.scala:145)
  org.http4s.internal.parboiled2.Parser.runRule$1(Parser.scala:143)
  org.http4s.internal.parboiled2.Parser.phase0_initialRun$1(Parser.scala:151)
  org.http4s.internal.parboiled2.Parser.__run(Parser.scala:204)
  org.http4s.Uri$.fromString(Uri.scala:145)
  ammonite.$sess.cmd2$.<init>(cmd2.sc:1)
  ammonite.$sess.cmd2$.<clinit>(cmd2.sc)
```

### PR DESCRIPTION
**Pull request by kevinmeredith**
Closes #2583 by implementing one of @rossabaker's suggestions from #2583 (comment).

Per https://github.com/http4s/http4s/pull/2664#issuecomment-506858839, I decided to close https://github.com/http4s/http4s/pull/2664 in favor of this PR.

### CODE REVIEW

File: tests/src/test/scala/org/http4s/UriSpec.scala [hunk 1]
```diff
@@ -84,6 +86,44 @@ http://example.org/a file
...
+        {
+          val uri: ParseResult[Uri] = Uri.fromString(s"http://localhost:$notNumber/")
+          uri match {
+            case Left(ParseFailure("Invalid URI", _)) => ok
+            case unexpected => ko(unexpected.toString)
+          }
+        }
+      }.setGen(Gen.alphaNumStr.suchThat(str =>
+        str.nonEmpty && Either.catchOnly[NumberFormatException](str.toInt).isLeft))
+      "for an empty String" in {
```
Comment (kevinmeredith) [inline tests/src/test/scala/org/http4s/UriSpec.scala]: Locally, this test failed:

```
[info]   fail to parse port
[info]     + if it's negative (214 ms)
[info]     + if it's larger than Int.MaxValue (230 ms)
[info]     + if it's not a number or an empty String (256 ms)
[error]     x for an empty String (271 ms)
[error]      Right(http://localhost/) (UriSpec.scala:121)
[error] org.http4s.UriSpec.$anonfun$new$51(UriSpec.scala:121)
```

@rossabaker. 

Per https://tools.ietf.org/html/rfc3986#page-22, 

```
3.2.3.  Port

   The port subcomponent of authority is designated by an optional port
   number in decimal following the host and delimited from it by a
   single colon (":") character.

      port        = *DIGIT

   A scheme may define a default port.  For example, the "http" scheme
   defines a default port of "80", corresponding to its reserved TCP
   port number.  The type of port designated by the port number (e.g.,
   TCP, UDP, SCTP) is defined by the URI scheme.  URI producers and
   normalizers should omit the port component and its ":" delimiter if
   port is empty or if its value would be the same as that of the
   scheme's default.
```

Per https://tools.ietf.org/html/rfc3986#page-22, 

```
6.2.3.  Scheme-Based Normalization

   The syntax and semantics of URIs vary from scheme to scheme, as
   described by the defining specification for each scheme.
   Implementations may use scheme-specific rules, at further processing
   cost, to reduce the probability of false negatives.  For example,
   because the "http" scheme makes use of an authority component, has a
   default port of "80", and defines an empty path to be equivalent to
   "/", the following four URIs are equivalent:

      http://example.com
      http://example.com/
      http://example.com:/
      http://example.com:80/
```

this test, it seems clear to me, should fail, not pass. In other words, I should replace this "should fail" test with a "should parse to port 80" one.

Please let me know if you disagree.

File: core/src/main/scala/org/http4s/parser/Rfc3986Parser.scala [hunk 2]
```diff
@@ -82,7 +82,9 @@ private[parser] trait Rfc3986Parser
 
   def Port = rule {
     ":" ~ (capture(oneOrMore(Digit)) ~> { s: String =>
-      (Some(s.toInt))
+      val int: Option[Int] = Either.catchOnly[NumberFormatException](s.toInt).toOption
```
Comment (kevinmeredith) [inline core/src/main/scala/org/http4s/parser/Rfc3986Parser.scala]: I was able to use your suggestion, https://github.com/http4s/http4s/pull/2664#discussion_r296258166, @SystemFw. Thanks for it!

File: tests/src/test/scala/org/http4s/UriSpec.scala (hunk 1 above)
Comment (ChristopherDavenport) [reply tests/src/test/scala/org/http4s/UriSpec.scala]: Yup, That seems correct via the spec.

**Comment by kevinmeredith** [comment]
I closed, and then re-opened, due to, what appears to be, a flaky test.

**Comment by kevinmeredith** [comment]
I need to address:

```scala
[error] /home/travis/build/http4s/http4s/core/src/main/scala/org/http4s/parser/Rfc3986Parser.scala:85:69: type mismatch;
[error]  found   : Either[NumberFormatException,Int]
[error]  required: ?{def toOption: ?}
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method EitherSyntax in package http4s of type [L, R](self: Either[L,R])org.http4s.package.EitherSyntax[L,R]
[error]  and method catsSyntaxEither in trait EitherSyntax of type [A, B](eab: Either[A,B])cats.syntax.EitherOps[A,B]
[error]  are possible conversion functions from Either[NumberFormatException,Int] to ?{def toOption: ?}
[error]       val int: Option[Int] = Either.catchOnly[NumberFormatException](s.toInt).toOption
[error]                                                                     ^
[error] one error found
[error] (core / Compile / compileIncremental) Compilation failed
[error] Total time: 67 s, completed Jul 2, 2019 2:27:51 PM
```

per latest build failure.

File: tests/src/test/scala/org/http4s/UriSpec.scala [hunk 3]
```diff
@@ -57,14 +57,23 @@ class UriSpec extends Http4sSpec with MustThrownMatchers {
...
+            val uri = getUri(s"http://localhost:$nonNegative/")
+            uri.port must_=== Some(nonNegative)
+          }
+        }.setGen(Gen.choose[Int](0, Int.MaxValue))
         "if there is none" in {
           val uri = getUri("http://localhost/")
           uri.port must_=== None
         }
+        // See RFC 3986, section 6.2.3
+        "for an empty String" in {
```
Comment (ChristopherDavenport) [inline tests/src/test/scala/org/http4s/UriSpec.scala]: Given `https://foobar:/` should this infer `443` rather than `80`? I worry as I believe some may rely on this behavior by accident and then they would go to the unsecured port by default.

Comment (rossabaker) [reply tests/src/test/scala/org/http4s/UriSpec.scala]: Are we inferring anywhere in the Uri?  We do in the clients, but the Uri has an optional port.  You're correct that the inference is scheme specific, but I think this test is right.

Comment (kevinmeredith) [reply tests/src/test/scala/org/http4s/UriSpec.scala]: > Given https://foobar:/ should this infer 443 rather than 80?

Is it worthwhile to open another issue, @ChristopherDavenport, if `https://foobar:/` resolves a port of 80 rather than 443? I'm only asking since, I believe, my PR addresses https://github.com/http4s/http4s/issues/2583.

**Comment by niij** [comment]
Thanks @kevinmeredith !

File: tests/src/test/scala/org/http4s/UriSpec.scala (hunk 3 above)
Comment (kevinmeredith) [reply tests/src/test/scala/org/http4s/UriSpec.scala]: Hi @ChristopherDavenport -

> Given https://foobar:/ should this infer 443 rather than 80?

So the following looks right or wrong to you? I admit to not knowing how the `Port` is used if there's a supplied `Scheme`, i.e. my first `Uri#fromString` REPL example.

```scala
@ import $ivy.`org.http4s::http4s-core:0.20.6` 
import $ivy.$                               

@ Uri.fromString("https://www.google.com:80") 
res5: org.http4s.package.ParseResult[Uri] = Right(Uri(Some(Scheme(https)), Some(Authority(None, RegName(www.google.com), Some(80))), "", , None))

@ Uri.fromString("https://www.google.com:/") 
res6: org.http4s.package.ParseResult[Uri] = Right(Uri(Some(Scheme(https)), Some(Authority(None, RegName(www.google.com), None)), "/", , None))
```

Does this look right, Chris?
