### PR TITLE
Deprecate Jsonp Middleware

### LINKED ISSUE #6959: Deprecate Jsonp middleware?
While trying to review a 1.x optimization of the Jsonp middleware (https://github.com/http4s/http4s/pull/6937) I wrote a test suite and found that the Jsonp middleware has perhaps been broken for a few years.
PR with failing tests: https://github.com/http4s/http4s/pull/6958

The problem is a complicated regex for validating the callback param.
It [changed two years ago](https://github.com/http4s/http4s/commit/d67539378a1bc65cfc10d5698c339fc34a1842c4#diff-9f712c6cea40b287988742a7ad4d26f2e05a325770c0b988cc7fd8d55d0f21d0) and perhaps broke (I haven't tested if the above test suite would pass using the older version).
We can perhaps fix the first `Illegal character range` error, but then the regex will still not work on scala native because of its use of look-aheads.
If we really want to continue supporting Jsonp middleware we should perhaps stop using a regex for the validation.

However, JSONP is also no longer recommended:

> JSONP is vulnerable to the data source replacing the innocuous function call with malicious code, which is why it has been superseded by cross-origin resource sharing (available since 2009[[3]](https://en.wikipedia.org/wiki/JSONP#cite_note-caniuse-cors-3)) in modern applications.
https://en.wikipedia.org/wiki/JSONP

I'm proposing we deprecate the middleware in series/0.23 and remove it from 1.x

### PR DESCRIPTION
**Pull request by froth**
fixes #6959

### CODE REVIEW

File: server/shared/src/main/scala/org/http4s/server/middleware/Jsonp.scala [hunk 1]
```diff
@@ -42,6 +42,8 @@ object Jsonp {
...
+
+  @deprecated("JSONP is deprecated, use CORS instead.", "0.23.24")
```
Comment (armanbilge) [inline server/shared/src/main/scala/org/http4s/server/middleware/Jsonp.scala:46]:
```suggestion
  @deprecated("JSONP is deprecated and will be removed without replacement in 1.x, use CORS instead.", "0.23.24")
```

**Review by armanbilge — COMMENTED** [review]
Thanks for chasing up on this! Looks great, let's point out that we are completely removing it.

**Comment by froth** [comment]
> Thanks for chasing up on this! Looks great, let's point out that we are completely removing it.

Good point. I have accepted your change.

**Comment by froth** [comment]
OK. I will run scalafmt tomorrow ;)

**Comment by froth** [comment]
Pipelines are appeased

**Review by danicheg — APPROVED** [review]
:saluting_face:
