### PR TITLE
Metrics fix

### LINKED ISSUE #1606: server-metrics don't handle requests to the `metricsService` correctly.
I tried out the server-metrics package today and its [BlazeServerExample](/http4s/http4s/blob/master/examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala).  Nice work, it looks really promising.  

An oddity that I noticed was that the `active_requests` would increment but not decrement when the "/metrics" endpoint is invoked. It seems that the code in Metrics HttpMiddleware would increment but because the `prefix` was not found, it would never call funciton `generalMetrics`.

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
1) GET /http4s/metrics does not increment counters (it’s not wrapped in the middleware)
2) GET /http4s/metrics does not leave a dangling active request
3) GET /http4s/dfdajkfldajfklddasfadskl does not leave a dangling active request. (This is one where a wrapped service returns None).
4) GET /http4s/ping increments 200 and does not leaving dangling active request

Closes #1606

### CODE REVIEW

File: server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala [hunk 1]
```diff
@@ -2,102 +2,183 @@ package org.http4s
...
+  private def manageResponse[F[_]: Sync](
+                                   m: Method,
+                                   elapsed: Long,
+                                   serviceMetrics: ServiceMetrics
+                                 )(response: Response[F]): Response[F] = {
+    val newBody = response.body
+      .onFinalize(
+        incrementCounts(serviceMetrics.generalMetrics.headers_times, elapsed) *>
+        requestMetrics(serviceMetrics.requestTimers, serviceMetrics.generalMetrics.active_requests)(m, elapsed) *>
+        responseMetrics(serviceMetrics.responseTimers, response.status, elapsed)
```
Comment (rossabaker) [inline server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala]: These aren't measuring all the way to the end of the body now, right?  That's the difference between `headers_times` and the other timers.  I think these two should be measured to when the finalizer triggers.

File: server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala [hunk 2]
```diff
@@ -2,102 +2,183 @@ package org.http4s
...
+    response.copy(body = newBody)
+  }
+
+  private def manageServiceErrors[F[_]: Sync](m: Method, elapsed: Long, serviceMetrics: ServiceMetrics): F[Unit] =
+    requestMetrics(serviceMetrics.requestTimers, serviceMetrics.generalMetrics.active_requests)(m, elapsed) *>
+    incrementCounts(serviceMetrics.responseTimers.resp5xx, elapsed) *>
+    incrementCounts(serviceMetrics.generalMetrics.service_errors, elapsed)
+
+
+  private def handleUnmatched[F[_]: Sync](c: Counter): F[Option[Response[F]]] =
```
Comment (rossabaker) [inline server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala]: If we increment 5xx on these, should we increment 4xx on this?  This is the dirty bit about doing metrics as middleware: we don't know what happens outside middleware.  Maybe we're chained to something that recovers.  Maybe the server handles it.  I think this is inconsistent with `manageServiceErrors`, though I don't have a strong feeling which direction to fix it.

Comment (ChristopherDavenport) [reply server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala]: Yeah. I can increment as it without it we don't match requirement 4

Comment (ChristopherDavenport) [reply server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala]: I question whether us projecting a response is the right move as well. Metrics on a service should measure what happens with that service. For metrics matching unmatched They should make the service total

Comment (rossabaker) [reply server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala]: :+1: I think we just count nones and errors and not double count as 4xx and 5xx. Which is a reversal of point 4 above, but I think correct.

**Comment by ChristopherDavenport** [comment]
Fixes #1606

File: server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala [hunk 3]
```diff
@@ -2,102 +2,203 @@ package org.http4s
...
+    val method = req.method
+    for {
+      now <- OptionT.liftF[F, Long](Sync[F].delay(System.nanoTime()))
+      _ <- OptionT.liftF[F, Unit](
+        Sync[F].delay(serviceMetrics.generalMetrics.active_requests.inc()))
+      resp <- OptionT {
         service(req).value.attempt
-          .flatMap(onFinish(req.method, now)(_)
-            .fold[F[Option[Response[F]]]](F.raiseError, F.pure))
+          .flatMap(metricsServiceHandler(method, now, serviceMetrics, _))
```
Comment (jmcardon) [inline server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala]: This block seems redundant to `liftF` multiple times, then wrap the last one. 

You can instead make the comprehension only in terms of `F` and wrap the whole thing. It would be better since `liftF` causes a `map(Some(_))`.

File: server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala [hunk 4]
```diff
@@ -2,102 +2,203 @@ package org.http4s
...
+      active_requests: Counter
+  )(method: Method, elapsed: Long): F[Unit] = {
+    val timer = requestTimer(rt, method)
+    incrementCounts(timer, elapsed) *>
+      incrementCounts(rt.total_req, elapsed) *>
+      Sync[F].delay(active_requests.dec())
   }
+
+  private case class RequestTimers(
+      get_req: Timer,
```
Comment (jmcardon) [inline server-metrics/src/main/scala/org/http4s/server/metrics/Metrics.scala]: re: gitter discussion, could we go ahead and maybe get rid of the snake case?
