### PR TITLE
Log errors in `upgradeSocket`

### LINKED ISSUE #7356: Broken Pipe error logs in Ember Server when using `withTLS`
similar to #7014 but for `withTLS` instead of `withHttp2`

```
scala 3.3.1
org.typelevel:cats-effect_3:3.5.2
co.fs2:fs2-core_3:3.9.3
org.http4s:http4s-core_3:0.23.25
```

I get error logs when killing curl requests against ember with TLS enabled:

``` scala
EmberServerBuilder
        .default[IO]
        .withHost(ipv4"0.0.0.0")
        .withPort(port"8443")
        .withTLS(tlsContext)
        .withHttpApp(finalHttpApp)
        .build
```
Error log:
```
root 2024-01-10 09:33:34,714 [ERROR]             [io-compute-10] o.h.e.server.EmberServerBuilderCompanionPlatform - Request handler failed with exception
root java.io.IOException: Broken pipe
root    at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
root    at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:62)
root    at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:137)
root    at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:102)
root    at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:65)
root    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishWrite(UnixAsynchronousSocketChannelImpl.java:602)
root    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:199)
root    at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217)
root    at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:305)
root    at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
root    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
root    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
root    at java.base/java.lang.Thread.run(Thread.java:1583)
root    at delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.go$2$$anonfun$1(SocketPlatform.scala:131)
root    at async @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.go$2(SocketPlatform.scala:131)
root    at flatMap @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.go$2(SocketPlatform.scala:135)
root    at delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.write(SocketPlatform.scala:138)
root    at flatMap @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.write(SocketPlatform.scala:138)
root    at apply @ org.http4s.ember.server.EmberServerBuilder.build$$anonfun$2(EmberServerBuilder.scala:216)
```

Broken pipes are errors, it is fine to log them but error loglevel is a little much in my opinion. I believe https://github.com/http4s/http4s/pull/7016 fixed something similar but it seems not to work for TLS.

### PR DESCRIPTION
**Pull request by froth**
fixes #7356 

Prevent error logs when client closes connection during socket upgrade.

### CODE REVIEW

File: ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala [hunk 1]
```diff
@@ -340,7 +340,9 @@ private[server] object ServerHelpers extends ServerHelpersPlatform {
               .withLogger(tlsLogger)
               .build
               .evalMap(tlsSocket =>
-                tlsSocket.write(fs2.Chunk.empty) >>
+                tlsSocket
+                  .write(fs2.Chunk.empty)
+                  .handleErrorWith(err => logger.warn(err)("Failed to upgrade socket to TLS")) >>
```
Comment (armanbilge) [inline ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala:345]: This completely suppresses the error—we no longer have short-circuiting. That means that `upgradeSocket` will return normally and return a dud socket.
https://github.com/http4s/http4s/blob/00165289e755e9c5d4b13451db3e33da05512a23/ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala#L195-L198

Comment (froth) [reply ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala:345]: One possible solution would be to do something like `handleErrorWith(e => Async[F].raiseError(CustomErrorType(e)))`

And pattern match it out here:
https://github.com/http4s/http4s/blob/00165289e755e9c5d4b13451db3e33da05512a23/ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala#L288C1-L292C12

Comment (armanbilge) [reply ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala:345]: Can we do something similar to this PR?
- https://github.com/http4s/http4s/pull/7157

Comment (froth) [reply ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala:345]: That could work, I think. I will have a deeper look tomorrow :)

File: ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala [hunk 2]
```diff
@@ -194,6 +194,8 @@ private[server] object ServerHelpers extends ServerHelpersPlatform {
         val handler: Stream[F, Nothing] = shutdown.trackConnection >>
           Stream
             .resource(upgradeSocket(connect, tlsInfoOpt, logger, enableHttp2))
+            .onError(err => Stream.eval(logger.warn(err)("Failed to upgrade socket to TLS")))
+            .mask
```
Comment (armanbilge) [inline ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala:198]: Maybe we can even simplify it to this:
```suggestion
            .handleErrorWith(err => Stream.exec(logger.warn(err)("Failed to upgrade socket to TLS")))
```

**Comment by froth** [comment]
@armanbilge I changed it to `onError` and `mask`. I was not sure whether only to handle the errors on tlsSocket.write or everything in upgradeSocket. I opted for the second.

That file feels a bit overwhelming to be honest, so maybe this is still way wrong :sweat_smile:

File: ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala (hunk 2 above)
Comment (froth) [reply ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala:198]: I thought so too but that does not compile because that log statement creates a `Stream[F, Unit]` which the compiler does not like

Comment (froth) [reply ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala:198]: ahhh no, I did not see the exec, thanks!

Comment (armanbilge) [reply ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala]: Are you sure? That sounds like `Stream.eval`, not `Stream.exec`.

Comment (froth) [reply ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala]: I saw that the second after sending the comment, the way my brain works lots of the time :joy_cat:

**Review by armanbilge — APPROVED** [review]
Nice job tracking this one down! log-level is bike-sheddable but this is already an improvement so we can leave that to subsequent PRs.
