### PR TITLE
Fix or exclude scalafix warnings

### LINKED ISSUE #5537: Lint is full of warnings on series/0.22
I painstakingly fixed a bunch of these, but I guess it was on a different branch, and there are bincompat concerns.  But when I run quicklint on series/0.22, [warnings abound](https://github.com/http4s/http4s/runs/4105585792?check_suite_focus=true).  Are we just living with those?  `@nowarn`ing them away some how?

### PR DESCRIPTION
**Pull request by bplommer**
Resolves #5537

### CODE REVIEW

File: core/src/main/scala/org/http4s/internal/CharPredicate.scala [hunk 1]
```diff
@@ -149,7 +149,7 @@ object CharPredicate {
   private def unmaskable(c: Char) = c >= 128
 
   // efficient handling of 7bit-ASCII chars
-  case class MaskBased private[CharPredicate] (lowMask: Long, highMask: Long)
+  sealed case class MaskBased private[CharPredicate] (lowMask: Long, highMask: Long)
```
Comment (danicheg) [inline core/src/main/scala/org/http4s/internal/CharPredicate.scala:152]: I'm still not convinced about having `sealed` case classes. They shouldn't be extendable at all, I believe.

**Review by danicheg — COMMENTED** [review]
Thanks for that work!

File: core/src/main/scala/org/http4s/internal/CharPredicate.scala (hunk 1 above)
Comment (bplommer) [reply core/src/main/scala/org/http4s/internal/CharPredicate.scala:152]: Right. We can make this final since the private constructor already makes it effectively final.

**Review by danicheg — APPROVED** [review]

**Review by rossabaker — APPROVED** [review]
