### PR TITLE
Fix `Client.fromHttpApp` does not drain bodies

### LINKED ISSUE #7018: `Client.fromHttpApp` does not drain bodies
This is especially a problem because finalizers are attached to the body, as demoed in this example which only prints "acquire" and not "release".

```scala
//> using lib "org.http4s::http4s-client::0.23.18"
//> using lib "org.http4s::http4s-server::0.23.18"

import cats.data._
import cats.effect._
import org.http4s._
import org.http4s.client._
import org.http4s.server.middleware._

object App extends IOApp.Simple {
  val app = BracketRequestResponse
    .bracketRequestResponseApp(IO.println("acquire"))(_ => IO.println("release"))
    .apply(Kleisli.pure(Response[IO]()))

  val client = Client.fromHttpApp(app)

  def run = client.status(Request()).void
}
```

h/t @fredshonorio

### PR DESCRIPTION
**Pull request by kovstas**
Fix #7018

### CODE REVIEW

**Comment by armanbilge** [comment]
Awesome, thanks for this! Sorry, I should have mentioned: do you mind rebasing and targeting your PR at `series/0.23` branch? The process we use is to do most work (fixes, compatible features) on `series/0.23`. PRs for `main` are for breaking changes.

**Comment by kovstas** [comment]
Sure, but do you mind if I move not only my changes but the whole `.run` method to `series/0.23`, because the current implementation `runOrDispose` method at `series/0.23` doesn't allow handling this case properly. I need to distinguish the request and the response disposing stage, `run` in `main` makes it much easier than `runOrDispose` at `series/0.23`.

**Comment by armanbilge** [comment]
Sure, whatever it takes to fix it! :)

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 1]
```diff
@@ -289,16 +290,37 @@ object Client {
...
+        Resource.eval(refOp.fold(Ref[F].of(false))(F.pure)).flatMap { r =>
+          Resource
+            .pure(resp.pipeBodyThrough(until(r)(_).onFinalizeCase {
+              case ExitCase.Canceled | ExitCase.Errored(_) => F.unit
+              case ExitCase.Succeeded => r.set(true)
+            }))
+            .onFinalize {
+              r.get.ifM(
+                F.unit,
+                resp.body.compile.drain.flatMap(_ => r.set(true)),
```
Comment (armanbilge) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:316]:
```suggestion
                resp.body.compile.drain.guarantee(r.set(true)),
```

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 2]
```diff
@@ -289,16 +290,37 @@ object Client {
...
+            .onFinalize(disposed.set(true))
+            .flatMap(run(_, Option(disposed)))
+        }
+      case resp: Response[F] =>
+        Resource.eval(refOp.fold(Ref[F].of(false))(F.pure)).flatMap { r =>
+          Resource
+            .pure(resp.pipeBodyThrough(until(r)(_).onFinalizeCase {
+              case ExitCase.Canceled | ExitCase.Errored(_) => F.unit
+              case ExitCase.Succeeded => r.set(true)
+            }))
```
Comment (armanbilge) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:312]: I need to think about this some more. What happens if there is an error / cancellation while the client is consuming the `Stream`? In that case, it will compile it again in the `onFinalize` before. But what bothers me is then it may be starting the stream again from the beginning.

I wonder if what we need to do is create an intermediate `fs2.concurrent.Channel` to drain the `Stream` into. That way, even if the client errors/cancels half-way through, the final drain at the end will pick up from where it left off, instead of recompiling from scratch.

It would be really great to add a test case to cover this situation.

Comment (armanbilge) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:312]: Oh! I think there may be another case. What happens if the stream ends successfully, without draining all the bytes? e.g. `stream.take(1).compile.drain` 🤔

I think a `Channel` might be the best solution here.

Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:312]: Yep, I think you are right. I will try to solve it with `Channel`, thanks for the idea!

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 3]
```diff
@@ -289,16 +291,40 @@ object Client {
...
+            addHostHeaderIfUriIsAbsolute(req.pipeBodyThrough(until(disposed)))
+          Resource
+            .eval(app(reqAugmented))
+            .onFinalize(disposed.set(true))
+            .flatMap(run(_, Option(disposed)))
+        }
+      case resp: Response[F] =>
+        for {
+          disposed <- Resource.eval(refOp.fold(Ref[F].of(false))(F.pure))
+          channel <- Resource.make(Channel.unbounded[F, Byte])(_.close.void)
```
Comment (armanbilge) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:310]: I think this should be a `Channel.synchronous`. Otherwise the entire response will go into memory, even before the client has requested it, so we lose backpressure. A `synchronous` stream will only request when the downstream has requested.

Also, `channel.sendAll(...)` closes the `Channel` automatically. Instead I feel like the `close` here should be draining the `Channel`.

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 4]
```diff
@@ -289,16 +291,40 @@ object Client {
...
+          r = resp.withBodyStream(
+            channel.stream
+              .through(until(disposed)(_))
+              .onFinalize(channel.stream.compile.drain.guarantee(disposed.set(true)))
+              .concurrently(channel.sendAll(resp.body))
```
Comment (armanbilge) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:315]: I'm not entirely sure if this is right, the issue with `concurrently` is that it will be interrupted as soon as the the primary stream is interrupted. And actually we don't want the `resp.body` stream to _ever_ be interrupted, that is the whole point of directing it into the `Channel`.

File: client/shared/src/test/scala/org/http4s/client/ClientSuite.scala [hunk 5]
```diff
@@ -147,4 +148,42 @@ class ClientSpec extends Http4sSuite with Http4sDsl[IO] {
...
+
+    for {
+      finalized <- Ref.of[IO, Boolean](false)
+      client = Client.fromHttpApp(app(finalized))
+      _ <- client.status(Request[IO]()).void
+      result <- finalized.get
+    } yield assertEquals(result, true)
+  }
+
+  test("mock client should drain the body if it has been partially") {
```
Comment (armanbilge) [inline client/shared/src/test/scala/org/http4s/client/ClientSuite.scala:168]: Besides testing that the body is drained, I think we also want to test that the stream is not compiled more than once.

File: client/shared/src/main/scala/org/http4s/client/Client.scala (hunk 4 above)
Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:315]: Please correct me if I'm wrong, but if the logic replaces the response stream with a new stream `resp.withBodyStream`, then the client should not be able to interrupt the original `resp.body`. 

I understood your comment about using `Channel` that the client can forward bytes from `resp.body` to `Channel` and use `channel.stream` as a body stream. And if the user interrupts reading the stream from the step where client stopped due to the `Channel` implementation the logic can drain the rest of bytes from the point where the user stopped. 

Did I understand you correctly?

Comment (armanbilge) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:315]: Let me "zoom" on the problem:
```scala
channel.stream.concurrently(channel.sendAll(resp.body))
```
In this case, if the client stops consuming the stream, then it will also interrupt the `concurrently` "background" stream.

> The resulting stream terminates upon termination of this stream. The background stream will be interrupted at that point.

https://github.com/typelevel/fs2/blob/24ea712f61d3276cc5798ffa00396a7fa9378d30/core/shared/src/main/scala/fs2/Stream.scala#L519-L520

Since the "background" stream is based on `resp.body`, that means that `resp.body` will be interrupted.

Let me know if that makes sense!

Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala]: Thanks for the clarification. I've added a unit test to cover this case.

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 6]
```diff
@@ -289,16 +291,64 @@ object Client {
...
+        }
+      case resp: Response[F] =>
+        for {
+          disposed <- Resource.eval(refOp.fold(Ref[F].of(false))(F.pure))
+          channel <- Resource.eval(Channel.synchronous[F, Byte])
+
+          _ <- resp.body
+            .evalMap(channel.send)
+            .takeWhile(_.isRight)
+            .onFinalize(channel.close.void)
```
Comment (armanbilge) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:315]: Isn't this the definition of `channel.sendAll` ? Why copy it here?
https://github.com/typelevel/fs2/blob/509d74fdcc5bf0735cabcf829d0a5ba21a949ed9/core/shared/src/main/scala/fs2/concurrent/Channel.scala#L147-L151

Comment (armanbilge) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:315]: Actually, I'm afraid this is sending byte-by-byte instead of chunk-by-chunk. We should probably change this to work in terms of chunks.

Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala]: > Isn't this the definition of channel.sendAll
I changed the implementation so often that I did not notice that I repeated the same thing. I've replaced it with sendAll.

> sending byte-by-byte instead of chunk-by-chunk
done

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 7]
```diff
@@ -289,16 +291,62 @@ object Client {
...
+
+          _ <- Resource.onFinalize {
+            channel.close.void.guarantee {
+              disposed.get
+                .ifM(
+                  F.unit,
+                  r.body.compile.drain.void,
+                )
+                .guarantee(disposed.set(true))
+            }
```
Comment (armanbilge) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:342]: Wouldn't this close the `channel` possibly while it's still being written to, in the background? It's not obvious to me why we should ever close it ourselves: the only time it should be closed is when the `sendAll` completes.

Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala]: You're right. I removed it.

File: client/shared/src/test/scala/org/http4s/client/ClientSuite.scala [hunk 8]
```diff
@@ -147,4 +148,119 @@ class ClientSpec extends Http4sSuite with Http4sDsl[IO] {
...
+      compiledCounter <- Ref.of[IO, Int](0)
+      byteCounter <- Ref.of[IO, Int](0)
+      channel <- Channel.unbounded[IO, Byte]
+      client = Client.fromHttpApp(app(channel, compiledCounter))
+      _ <- client
+        .run(Request[IO]())
+        .use { r =>
+          r.body
+            .evalTap(_ => byteCounter.update(_ + 1))
+            .interruptWhen(fs2.Stream.eval(byteCounter.get.map(_ > 1)))
```
Comment (armanbilge) [inline client/shared/src/test/scala/org/http4s/client/ClientSuite.scala:252]: I think this is the same?
```suggestion
            .take(1)
```

File: client/shared/src/test/scala/org/http4s/client/ClientSuite.scala [hunk 9]
```diff
@@ -147,4 +148,119 @@ class ClientSpec extends Http4sSuite with Http4sDsl[IO] {
...
+
+    for {
+      compiledCounter <- Ref.of[IO, Int](0)
+      channel <- Channel.unbounded[IO, Byte]
+      client = Client.fromHttpApp(app(channel, compiledCounter))
+      result <- client
+        .run(Request[IO]())
+        .use { r =>
+          r.body
+            .merge(fs2.Stream.raiseError[IO](new Exception(expectedErrorMsg)))
```
Comment (armanbilge) [inline client/shared/src/test/scala/org/http4s/client/ClientSuite.scala:215]:
```suggestion
          r.body
            .evalTap(_ => IO.raiseError(new Exception(expectedErrorMsg))
```

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 10]
```diff
@@ -289,16 +291,59 @@ object Client {
...
+      case resp: Response[F] =>
+        for {
+          disposed <- Resource.eval(refOp.fold(Ref[F].of(false))(F.pure))
+          channel <- Resource.eval(Channel.synchronous[F, Chunk[Byte]])
+
+          _ <- resp.body.chunks
+            .through(channel.sendAll)
+            .compile
+            .drain
+            .background
```
Comment (armanbilge) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:316]:
```suggestion
            .drain
            .uncancelable
            .background
```

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 11]
```diff
@@ -289,16 +291,59 @@ object Client {
...
+          ifDisposed = Stream
+            .eval(disposed.get)
+            .ifM(
+              Stream.eval(F.raiseError(new IOException("response was disposed"))),
+              Stream.empty,
+            )
+
+          r = resp.withBodyStream(
+            channel.stream.unchunks
+              .ifEmpty(ifDisposed)
```
Comment (armanbilge) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:327]: Should we just check `disposed` first, does it matter if it is empty?

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 12]
```diff
@@ -289,16 +291,59 @@ object Client {
...
+                  .guarantee(disposed.set(true))
+              )
+          )
+
+          _ <- Resource.onFinalize {
+            disposed.get
+              .ifM(
+                F.unit,
+                r.body.compile.drain,
+              )
```
Comment (armanbilge) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:339]: Should this also `disposed.set(true)`? In case user tries to consume outside of `use` block.

Also, probably this doesn't need to be conditional, it should be safe to just drain again.

**Review by armanbilge — COMMENTED** [review]
Took another look at this and added some comments. It's pretty complicated actually! I think we've covered all the cases now 🤔  Thanks for your work on it 😁

File: client/shared/src/main/scala/org/http4s/client/Client.scala (hunk 11 above)
Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:327]: We can do it, but I'm not sure if we really need to because the logic drains the body in `onFinalize`, and `channel.stream` won't return anything except an empty stream. Additionally, I believe we can remove this exception in main since using `Channel` makes it impossible to recompile the response, and this exception is only needed to maintain the same contract.

File: client/shared/src/main/scala/org/http4s/client/Client.scala (hunk 12 above)
Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:339]: It can be unconditional if we don't have to return the `disposed` exception.

Comment (armanbilge) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:339]: > I noticed that it calls the body stream which has this logic in the final condition, so it will be executed in any case. Additionally, it should be conditional; otherwise, the logic will trigger the disposed error check in the body stream.

Oh, sorry, I missed that! Right, you are calling `r.body.compile.drain`, not `channel.stream.compile.drain`. I think this is fine then 👍

File: client/shared/src/main/scala/org/http4s/client/Client.scala (hunk 11 above)
Comment (armanbilge) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:327]: Right, I think it's about communicating intent i.e. if `disposed` is `true`, we should raise an error immediately, without doing anything else.

Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:327]: I forgot to mention that since `channel.stream` always returns an empty stream, any map or tap operation isn't invoked. Therefore, I found the `.isEmpty` method useful to maintain the contract. In reality, it doesn't do anything else. For the same reason, I removed `until(disposed))` from the response body stream. There is no case where it fires due to the "Channel" logic.

Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:327]: I'm wondering if you mean that the whole body stream should be started with `Stream.eval(disposed.get)` check? Like:
```scala
Stream
   .eval(disposed.get)
   .ifM(
       Stream.eval(F.raiseError(new IOException("response was disposed"))),
       channel.stream....,
    )
```

Comment (armanbilge) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:327]: Yes, exactly that! Sorry I wasn't clear.

File: client/shared/src/test/scala/org/http4s/client/ClientSuite.scala (hunk 8 above)
Comment (kovstas) [reply client/shared/src/test/scala/org/http4s/client/ClientSuite.scala:252]: You right. Then this test case is a duplicate of "..partially consumed". I will remove it.

**Comment by kovstas** [comment]
It seems that `ChunkAggregator` is broken now. I will try to figure out what is the cause.

File: docs/docs/server-middleware.md [hunk 13]
```diff
@@ -32,6 +32,7 @@ val service = HttpRoutes.of[IO] {
   case GET -> Root / "bad" => BadRequest()
   case GET -> Root / "ok" => Ok()
   case r @ POST -> Root / "post" => r.as[Unit] >> Ok()
+  case r @ POST -> Root / "postText" => r.as[String].flatMap(Ok(_))
```
Comment (armanbilge) [inline docs/docs/server-middleware.md:35]: We could also re-use the `reverse` route.

Comment (kovstas) [reply docs/docs/server-middleware.md:35]: I thought about that, but I decided it might be confusing because the logic already includes duplication from a middleware. Adding reversing from the route would make it even more complex, I think.

Comment (armanbilge) [reply docs/docs/server-middleware.md:35]: Makes sense. Maybe we should name this route `/echo`, since the response echoes the request?

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 14]
```diff
@@ -289,16 +291,57 @@ object Client {
...
+            addHostHeaderIfUriIsAbsolute(req.pipeBodyThrough(until(disposed)))
+          Resource
+            .eval(app(reqAugmented))
+            .onFinalize(disposed.set(true))
+            .flatMap(run(_, Option(disposed)))
+        }
+      case resp: Response[F] =>
+        for {
+          disposed <- Resource.eval(refOp.fold(Ref[F].of(false))(F.pure))
+          channel <- Resource.eval(Channel.synchronous[F, Chunk[Byte]])
```
Comment (armanbilge) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:310]: Everything looks great and the tests you added are excellent. Along those lines, if you don't mind, I have one last suggestion: can we add a test that will fail if this is switched to a `Channel.unbounded`? Something to verify that the body is not loaded into memory.

Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:310]: Nice idea! The test intercepts the moment the publication is completed before the response body is read by the client. Unfortunate, I had to use `IO.sleep` there to wait when the publication will be completed. I couldn't come up with any better approach to handle this. The logic might wait for a value of the `completed` to be true, but it can cause excessive waiting in the case when the logic uses `Channel.synchronous`.

File: client/shared/src/test/scala/org/http4s/client/ClientSuite.scala [hunk 15]
```diff
@@ -147,4 +150,104 @@ class ClientSpec extends Http4sSuite with Http4sDsl[IO] {
...
+      compiled <- compiledCounter.get
+    } yield {
+      assertEquals(result, entity.take(1).toSeq.toVector)
+      assertEquals(resultWithDrained, entity.toSeq.toVector)
+      assertEquals(compiled, 1)
+    }
+
+  }
+
+  test("mock client should fail if the internal channel is not synchronous") {
```
Comment (armanbilge) [inline client/shared/src/test/scala/org/http4s/client/ClientSuite.scala:197]:
```suggestion
  test("mock client should not read the body eagerly") {
```

File: client/shared/src/test/scala/org/http4s/client/ClientSuite.scala [hunk 16]
```diff
@@ -147,4 +150,104 @@ class ClientSpec extends Http4sSuite with Http4sDsl[IO] {
...
+
+    def app(compiled: Ref[IO, Int]) = HttpApp[IO] { (_: Request[IO]) =>
+      Response[IO]()
+        .withEntity("foo")
+        .pipeBodyThrough(_.onFinalize(compiled.update(_ + 1)))
```
Comment (armanbilge) [inline client/shared/src/test/scala/org/http4s/client/ClientSuite.scala:202]:
```suggestion
        .pipeBodyThrough(Stream.exec(compiled.update(_ + 1)) ++ _)
```

File: client/shared/src/test/scala/org/http4s/client/ClientSuite.scala [hunk 17]
```diff
@@ -147,4 +150,104 @@ class ClientSpec extends Http4sSuite with Http4sDsl[IO] {
...
+
+    for {
+      compiledCounter <- Ref.of[IO, Int](0)
+      client = Client.fromHttpApp(app(compiledCounter))
+      _ <- client.run(Request[IO]()).use { _ =>
+        IO.sleep(1.millis) *>
+          compiledCounter.get.assertEquals(0)
+      }
+      _ <- compiledCounter.get.assertEquals(1)
+    } yield ()
```
Comment (armanbilge) [inline client/shared/src/test/scala/org/http4s/client/ClientSuite.scala:214]: We can use `executeEmbed` for reliable, time-based tests, since it uses a simulated clock :)

```suggestion
    val test = for {
      compiledCounter <- Ref.of[IO, Int](0)
      client = Client.fromHttpApp(app(compiledCounter))
      _ <- client.run(Request[IO]()).use { _ =>
        IO.sleep(1.second) *>
          compiledCounter.get.assertEquals(0)
      }
      _ <- compiledCounter.get.assertEquals(1)
    } yield ()
    
    TestControl.executeEmbed(test)
```

File: client/shared/src/main/scala/org/http4s/client/Client.scala (hunk 14 above)
Comment (armanbilge) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:310]: > The logic might wait for a value of the `completed` to be true, but it can cause excessive waiting in the case when the logic uses `Channel.synchronous`.

Oh, actually that might be another good approach. I added some suggestions about using the `executeEmbed` test runtime which uses simulated time. With that one, you can actually verify that an `IO` never completes. So maybe we can write the test like that?

Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:310]: Thanks! Now, it's better.

File: client/shared/src/test/scala/org/http4s/client/ClientSuite.scala [hunk 18]
```diff
@@ -194,24 +195,26 @@ class ClientSpec extends Http4sSuite with Http4sDsl[IO] {
...
   }
 
-  test("mock client should fail if the internal channel is not synchronous") {
+  test("mock client should not read the body eagerly") {
 
     def app(compiled: Ref[IO, Int]) = HttpApp[IO] { (_: Request[IO]) =>
       Response[IO]()
         .withEntity("foo")
-        .pipeBodyThrough(_.onFinalize(compiled.update(_ + 1)))
+        .pipeBodyThrough(_ ++ fs2.Stream.exec(compiled.update(_ + 1)))
```
Comment (armanbilge) [inline client/shared/src/test/scala/org/http4s/client/ClientSuite.scala]: I was thinking the `exec` should come first, did the test not pass like this?

Comment (kovstas) [reply client/shared/src/test/scala/org/http4s/client/ClientSuite.scala]: Yep, it didn't pass

Comment (armanbilge) [reply client/shared/src/test/scala/org/http4s/client/ClientSuite.scala]: Interesting! So I guess the `exec` is executed eagerly then, did not know that.

**Review by armanbilge — APPROVED** [review]
Really great job on this! Thanks for bearing with me through the review cycle :)

If you are interested (no pressure!) this one might be an interesting follow-up issue.
- https://github.com/http4s/http4s/issues/6590

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 19]
```diff
@@ -289,16 +291,57 @@ object Client {
...
+            .compile
+            .drain
+            .uncancelable
+            .background
+
+          r = resp.withBodyStream(
+            Stream
+              .eval(disposed.get)
+              .ifM(
+                Stream.eval(F.raiseError(new IOException("response was disposed"))),
```
Comment (danicheg) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:323]:
```suggestion
                Stream.raiseError[F](new IOException("response was disposed")),
```

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 20]
```diff
@@ -289,16 +291,57 @@ object Client {
...
+                r.body.compile.drain,
+              )
+          }
+
+        } yield r
+
+    }
 
-    Client((req: Request[F]) => Resource.suspend(runOrDispose(req)))
+    Client((req: Request[F]) => run(req))
```
Comment (danicheg) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:344]: Hmm, if we only pass `Request`s to `run`, why do we handle the `Message` then?

**Review by danicheg — COMMENTED** [review]
Passing through, just a few comments

File: client/shared/src/main/scala/org/http4s/client/Client.scala (hunk 20 above)
Comment (armanbilge) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:344]: Yes great eye! I noticed this as well :) I think it would be a lot clearer if we split it into two methods, instead of using a pattern match an `Option`. I didn't want to keep piling onto this PR 😅 but I would also really like to see this change!!

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 21]
```diff
@@ -289,16 +291,54 @@ object Client {
...
+
+        r = response.withBodyStream(
+          Stream
+            .eval(disposed.get)
+            .ifM(
+              Stream.raiseError[F](new IOException("response was disposed")),
+              channel.stream.unchunks
+                .onFinalize(
+                  channel.stream.compile.drain
+                    .guarantee(disposed.set(true))
```
Comment (danicheg) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:316]: Is this setting `disposed` to `true` a thing if we run the stream after the final check is performed (322-326 lines of this PR)?

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 22]
```diff
@@ -289,16 +291,54 @@ object Client {
...
+    ): Resource[F, Response[F]] =
+      for {
+        channel <- Resource.eval(Channel.synchronous[F, Chunk[Byte]])
+
+        _ <- response.body.chunks
+          .through(channel.sendAll)
+          .compile
+          .drain
+          .uncancelable
+          .background
```
Comment (danicheg) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:306]: Will this make sense if `disposed` is `true`?

**Review by danicheg — APPROVED** [review]
This is super cool work, and I don't want to block the merge! Left my comments just to satisfy my curiosity.

File: client/shared/src/main/scala/org/http4s/client/Client.scala (hunk 21 above)
Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:316]: Yep. It happens becuase the final check uses the body's stream that contains the `disposed` setting rather than the `channel.stream`.

File: client/shared/src/main/scala/org/http4s/client/Client.scala (hunk 22 above)
Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:306]: I don't think it matters, because the resource is already closed when `disposed` is `true`. The user can only try to re-read the body, that contains this check.

Comment (armanbilge) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:306]: Hm, actually I just realized there may be a problem here 🤔 😅 

What happens if this step of the resource completes, but then it is canceled right here, before creating the `Response`? It will try to clean up by stopping this background fiber, but it can't, because it's `uncancelable`, and it will never complete naturally because the `onFinalize` to `drain` it hasn't been registered yet 🤔 

I think we have to keep the `uncancelable`, because we learned that starting this `background` will run some tasks eagerly. So as soon as we start it I think we must finish it.

Maybe instead of using `background` we do a custom `Resource.make(...)(...)` that starts the fiber and makes sure to drain the channel in the finalizer.

Comment (kovstas) [reply client/shared/src/main/scala/org/http4s/client/Client.scala:308]: If the main point is to drain the channel, then I think we can ignore the background process and add the finalizer to the release stage of the channel.

File: client/shared/src/main/scala/org/http4s/client/Client.scala [hunk 23]
```diff
@@ -296,16 +297,15 @@ object Client {
...
 
-        _ <- response.body.chunks
+        producer = response.body.chunks
           .through(channel.sendAll)
           .compile
           .drain
           .uncancelable
-          .background
+
+        _ <- Resource.make(producer.start)(_ => channel.stream.compile.drain).map(_.join)
```
Comment (armanbilge) [inline client/shared/src/main/scala/org/http4s/client/Client.scala:308]: We are discarding the result anyway, so no point to `.map`. And I think it's good practice to `join` the fiber after `draining` just to be sure that it completed.

```suggestion
        _ <- Resource.make(producer.start)(f => channel.stream.compile.drain *> f.join.void)
```

**Comment by armanbilge** [comment]
Ok let's merge this before we think of anything else to do 😂
