### PR TITLE
Minimal support for hashed passwords in basicAuth

### LINKED ISSUE #730: Support for Password Hashing with Basic Authentication
The `BasicAuthentication` class does not work with hashed passwords. In particular, the design of `checkAuth` requires that the server store plaintext passwords or be able to decrypt them:

``` scala
  private def checkAuth(realm: String, store: AuthenticationStore, req: Request): Task[AuthReply] = {
    req.headers.get(Authorization) match {
      case Some(Authorization(BasicCredentials(user, client_pass))) =>
        store(realm, user).map {
          case None => NeedsAuth
          case Some(server_pass) =>
            if (server_pass == client_pass) OK(user, realm)
   ...
```

(from [BasicAuthentication.scala](https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/middleware/authentication/BasicAuthentication.scala#L32))

Note the test `server_pass == client_pass`; `server_pass` comes from the `store` function (which is fine). `client_pass` comes from the HTTP client, and there is no way to transform the value before comparing it to `server_pass`. Therefore, we cannot hash `client_pass` and compare it with some previously stored value (like the client's hashed, salted password).  Instead, `server_pass` must either be the plaintext equivalent of `client_pass`, which means we cannot store it as a hashed value.

I propose extending `store` so it takes the `client_pass` value and returns a value indicating if the user is authorized or not, rather than having the password comparison in this class.

### PR DESCRIPTION
**Pull request by m4dc4p**
Basic Authentication module now supports passing the cleartext password to a function which can validate the password (for example, by comparing it against a hashed value). Previously, the basic authentication middleware require that the password be stored in plaintext on the server.

Closes #730.

### CODE REVIEW

File: server/src/main/scala/org/http4s/server/middleware/authentication/BasicAuthentication.scala [hunk 1]
```diff
@@ -14,22 +14,56 @@ import scalaz.concurrent.Task
...
+    */
+  def apply(realm: String, validate: ValidatePassword): AuthMiddleware[(String, String)] = {
+    challenged(Service.lift { req =>
+      getChallenge(realm, validate, req, validatePassword _)
+    })
+  }
+
+  /**
+    * Construct authentication middleware that compares the client-provided password
+    * to a plaintext password stored on the server.
```
Comment (rossabaker) [inline server/src/main/scala/org/http4s/server/middleware/authentication/BasicAuthentication.scala]: Storing it this way is bad practice.  If someone really wants to do this, they can write a non-hashing `validatePassword`.  I'd be okay with eliminating this.

File: server/src/main/scala/org/http4s/server/middleware/authentication/package.scala [hunk 2]
```diff
@@ -7,9 +7,17 @@ import scalaz.concurrent.Task
...
+  type Realm = String
+  type User = String
+  type ClientPasssword = String
   // A function mapping (realm, username) to password, None if no password
   // exists for that (realm, username) pair.
-  type AuthenticationStore = (String, String) => Task[Option[String]]
+  type AuthenticationStore = (Realm, User) => Task[Option[String]]
+  /**
+    *  Validates a plaintext password (presumably by comparing it to a hashed value).
+    *  Some(true) means the password given is valid.
```
Comment (rossabaker) [inline server/src/main/scala/org/http4s/server/middleware/authentication/package.scala]: Maybe a sealed trait is more expressive for this ternary logic: Authenticated | IncorrectPassword | NoSuchUser.

It's not uncommon to have authentication backends that don't disclose whether the account exists on failure.  Does this require a fourth result type to express "It's not valid, but I'm not going to tell you why?"  I'm not sure.

**Comment by reactormonk** [comment]
I advertised `AuthMiddleware` for a common interface, which is being used here. That's about all I have to say in that regard.

You could add another page to the docs which lists presupplied authentication, and how to use it. The current `auth.md` tells you how to construct a `AuthMiddleware`, but it's less centered around actually using one that's already defined.

**Comment by m4dc4p** [comment]
@reactormonk @rossabaker Updated based on your review.

I looked at auth.md but didn't make any changes - adding examples would require more wordsmithing than I can do right now.

**Comment by m4dc4p** [comment]
I'm not sure how to fix the tut error that caused Travis to fail ...

**Comment by rossabaker** [comment]
That's an intermittent error in Travis with the clients.  (The timeout specs also fail from time to time, on Travis only.)  I'd love to get to the bottom of it, but it's not new.

File: server/src/main/scala/org/http4s/server/middleware/authentication/package.scala [hunk 3]
```diff
@@ -10,14 +10,16 @@ package object authentication {
...
+    * exists for that (realm, username) pair.
+    */
   type AuthenticationStore = (Realm, User) => Task[Option[String]]
   /**
     *  Validates a plaintext password (presumably by comparing it to a hashed value).
-    *  Some(true) means the password given is valid.
+    *  A Some value indicates success; None indicates the password failed to validate.
     */
-  type ValidatePassword = (Realm, User, ClientPasssword) => Task[Option[Boolean]]
+  type AuthenticationValidator = (Realm, User, ClientPasssword) => Task[Option[Unit]]
```
Comment (rossabaker) [inline server/src/main/scala/org/http4s/server/middleware/authentication/package.scala]: `Option[Unit]` feels awkward to me.  I think this is either a `Boolean` (which is often a smell) or an ADT.  Might it make sense for this to just return the `AuthReply`?  Would involve making that public.

**Comment by rossabaker** [comment]
Maybe there is a real problem with tut here.  I've got three failures in a row.  Going to try it locally.
