### PR TITLE
Fix StatusSpec sanitization property

### LINKED ISSUE #5736: Flaky test org.http4s.StatusSpec.rendering sanitizes statuses
https://github.com/http4s/http4s/runs/4509815005?check_suite_focus=true#step:13:662

### PR DESCRIPTION
**Pull request by rossabaker**
`0x80` is allowed, too.

Fixes #5736,

### CODE REVIEW

File: tests/src/test/scala/org/http4s/StatusSpec.scala [hunk 1]
```diff
@@ -121,12 +121,21 @@ class StatusSpec extends StatusDeprecatedSpec {
     }
   }
 
+  override def scalaCheckInitialSeed = "mHH4n4bmIN0r6i0yhujk-zIfZh6qXllsgrjAdMptTrO="
+
+  def isSanitized(s: Status): Boolean =
+    s.renderString
+      .getBytes(StandardCharsets.ISO_8859_1)
+      .forall(b => (b == ' ' || b == '\t' || (b >= 0x21 && b <= 0x7e) || ((b & 0xff) >= 0x80)))
```
Comment (rossabaker) [inline tests/src/test/scala/org/http4s/StatusSpec.scala:129]: The salient change is the `>=` in `((b & 0xff) >= 0x80)))`

**Review by RafalSumislawski — APPROVED** [review]

File: tests/src/test/scala/org/http4s/StatusSpec.scala [hunk 2]
```diff
@@ -121,12 +121,21 @@ class StatusSpec extends StatusDeprecatedSpec {
     }
   }
 
+  override def scalaCheckInitialSeed = "mHH4n4bmIN0r6i0yhujk-zIfZh6qXllsgrjAdMptTrO="
```
Comment (danicheg) [inline tests/src/test/scala/org/http4s/StatusSpec.scala:124]: That is no more needed, I guess
```suggestion
```

**Review by danicheg — APPROVED** [review]

File: tests/src/test/scala/org/http4s/StatusSpec.scala (hunk 2 above)
Comment (rossabaker) [reply tests/src/test/scala/org/http4s/StatusSpec.scala:124]: Oops.  Good catch.
