### PR TITLE
Fix false negative in UserInfo parsing test

### LINKED ISSUE #2944: UserInfos: reject userinfos with invalid characters
Hit this in an unrelated PR:

```
[error]   x reject userinfos with invalid characters (376 ms)
[error]    Falsified after 1 passed tests.
[error]    > ARG_0: "+"
[error]    The seed is TqslytqDInIEdPOhRix7yNUhmhNq3vpzfe8O_zHpfdM=
[error]    
[error]    > Right(UserInfo(+,None)) is not Left (UserInfoSpec.scala:77)
```

### PR DESCRIPTION
**Pull request by bfdes**
Fixes #2944.

### CODE REVIEW

File: tests/src/test/scala/org/http4s/UserInfoSpec.scala [hunk 1]
```diff
@@ -73,7 +73,7 @@ class UserInfoSpec extends Http4sSpec {
     }
 
     "reject userinfos with invalid characters" in prop { s: String =>
-      !s.forall(CharPredicate.Alpha ++ UrlCodingUtils.Unreserved ++ ":") ==>
+      !s.forall(Unreserved ++ GenDelims ++ SubDelims ++ ":") ==>
```
Comment (bfdes) [inline tests/src/test/scala/org/http4s/UserInfoSpec.scala]: Tested by hardcoding `s` to `+`.

File: core/src/main/scala/org/http4s/util/UrlCoding.scala [hunk 2]
```diff
@@ -14,6 +14,12 @@ private[http4s] object UrlCodingUtils {
   val Unreserved =
     CharPredicate.AlphaNum ++ "-_.~"
 
+  val GenDelims =
```
Comment (bfdes) [inline core/src/main/scala/org/http4s/util/UrlCoding.scala]: Taken from `Rfc3986Parser` and `QueryParser`.
