### PR TITLE
Fix Method.fromString

### LINKED ISSUE #3680: org.http4s.Method.fromString may succeed on invalid inputs
The initial conversation is [here](https://gitter.im/http4s/http4s-dev?at=5f55d832ec534f584fea2572)

Consider the example:
```
scala> Method.fromString("FOO:BAR")
val res: org.http4s.ParseResult[org.http4s.Method] = Right(FOO)
```
In other words, although the entire input string `"FOO:BAR"` is not a valid token, but its initial part `"FOO"` gets captured since it is still a token.
Therefore, `fromString` captures everything up to the first non-token symbol but not necessarily to the end of the entire input string.

Expected behavior: `Method.fromString("FOO:BAR")` should fail to create `Method`, i.e. return `Left(...)`.

### PR DESCRIPTION
**Pull request by satorg**
Should resolve #3680
Fixes the `Rfc2616BasicRules.token` method which is used in `Method.fromString`.
The `Rfc2616BasicRules.isToken` method should also get fixed.

### CODE REVIEW

File: tests/src/test/scala/org/http4s/MethodSpec.scala [hunk 1]
```diff
@@ -26,10 +29,33 @@ class MethodSpec extends Http4sSpec {
 
   "only tokens are valid methods" in {
     prop { (s: String) =>
+      // TODO: this check looks meaningless: `fromString` mostly relies on `Rfc2616BasicRules.token`
+      //       and the result is compared to `isToken` which calls to `Rfc2616BasicRules.token` as well.
```
Comment (rossabaker) [inline tests/src/test/scala/org/http4s/MethodSpec.scala:33]: Yeah, it's difficult to avoid repeating implementation in some property tests.  These kind of properties guard against future optimizations that break the contract, but that's unlikely here.

**Review by rossabaker — APPROVED** [review]
Looks great.
