### PR TITLE
Fix for multithreaded xml parsing

### LINKED ISSUE #1209: Parallel parsing of xml responses produces a null
A client that parses the response using XML fails when run in parallel. It produces some null xml responses. 

For example this expression:

```
httpClient.expect[Elem](target).map { xml =>
```

Will work fine on a single request but fail when several are done in parallel. producing a `null` xml

### PR DESCRIPTION
**Pull request by cquiroz**
This PR is a fix for #1209 it includes tests and a fix.

The fix is up for discussion as it changes the way an implicit decoder is built. I can see the argument both way of keeping the parser injectable or create one by default, but the approach on this PR gives a saner default and will fix #1209 

If this is accepted I'll port it to the 0.17.x branch

Fixes #1209

### CODE REVIEW

File: scala-xml/src/main/scala/scalaxml/ElemInstances.scala [hunk 1]
```diff
@@ -8,7 +8,11 @@ import scala.util.control.NonFatal
 import scala.xml._
 import scalaz.concurrent.Task
 
+import javax.xml.parsers.SAXParserFactory
+
 trait ElemInstances {
+  private val spf = SAXParserFactory.newInstance()
```
Comment (ChristopherDavenport) [inline scala-xml/src/main/scala/scalaxml/ElemInstances.scala]: Is this stateful?

File: scala-xml/src/main/scala/scalaxml/ElemInstances.scala [hunk 2]
```diff
@@ -22,12 +26,13 @@ trait ElemInstances {
...
    * @return an XML element
    */
-  implicit def xml(implicit parser: SAXParser = XML.parser): EntityDecoder[Elem] = {
+  implicit val xml: EntityDecoder[Elem] = {
     import EntityDecoder._
     decodeBy(MediaType.`text/xml`, MediaType.`text/html`, MediaType.`application/xml`){ msg =>
       collectBinary(msg).flatMap[Elem] { arr =>
         val source = new InputSource(new StringReader(new String(arr.toArray, msg.charset.getOrElse(Charset.`US-ASCII`).nioCharset)))
-        try DecodeResult.success(Task.now(XML.loadXML(source, parser)))
+        val saxParser = spf.newSAXParser()
```
Comment (ChristopherDavenport) [inline scala-xml/src/main/scala/scalaxml/ElemInstances.scala]: Same, does this manipulate state in a way we should be considerring.

File: scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala [hunk 3]
```diff
@@ -29,6 +31,14 @@ class ScalaXmlSpec extends Http4sSpec {
       getBody(resp.body) must_== ("html".getBytes)
     }
 
+    "parse XML in parallel" in {
+      // https://github.com/http4s/http4s/issues/1209
+      val pool = Executors.newFixedThreadPool(5)
```
Comment (ChristopherDavenport) [inline scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala]: Should this use the testong thread pool from Http4sSpec?

File: scala-xml/src/main/scala/scalaxml/ElemInstances.scala (hunk 2 above)
Comment (cquiroz) [inline scala-xml/src/main/scala/scalaxml/ElemInstances.scala]: I think not. This creates a new parser in each request instead of relying on the external parser which is not thread safe

File: scala-xml/src/main/scala/scalaxml/ElemInstances.scala (hunk 1 above)
Comment (cquiroz) [inline scala-xml/src/main/scala/scalaxml/ElemInstances.scala]: That's a good question. Creating the sax parser factory actually reads the configuration to decide what parser to use. I guess it is not strictly pure though the configuration probably never changes after you start the JVM

Any ideas on how to isolate this?

File: scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala (hunk 3 above)
Comment (cquiroz) [inline scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala]: Right, what's the pool provided by `Http4Spec`?

Comment (rossabaker) [inline scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala]: It's in the `Http4sSpec` companion object.

File: scala-xml/src/main/scala/scalaxml/ElemInstances.scala (hunk 1 above)
Comment (rossabaker) [inline scala-xml/src/main/scala/scalaxml/ElemInstances.scala]: Make this an abstract def, and implement it as `SAXParserFactory.newInstance()` in the package object?  Then anyone needing customization can extend `ElemInstances` and import that instead of the package object.  Similar to how pretty printing is made configurable in JSON.

**Comment by cquiroz** [comment]
Changed as requested

File: scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala (hunk 3 above)
Comment (ChristopherDavenport) [inline scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala]: [org.http4s.Http4sSpec.TestPool](https://github.com/http4s/http4s/blob/release-0.16.x/testing/src/test/scala/org/http4s/Http4sSpec.scala#L145) is the implementation I believe.

**Comment by cquiroz** [comment]
Rebased and ready to merge

**Comment by ChristopherDavenport** [comment]
Did I miss something? We talked about switching to TestPool, but then where the comment was made never was addressed, although it was addressed in one spot, and then it got approved and merged.

So what happened? Feels like the review process went a bit off course here.

**Comment by cquiroz** [comment]
Sorry my bad, I fixed it in one spot and forgot the other
