### PR TITLE
Router should use correct prefix when routing

### LINKED ISSUE #3713: Incorrect path composing with Router
**Problem:**
If the prefix used in `Router` contains more the one path fragment,  `Router` will always return `Not Found` error.

```
val ordersRoutes = HttpRoutes.of {
    case GET -> Root / "orders" => Ok("orders list")
}

val routes = Router("/api/v1/" -> ordersRoutes)
```

**Expected result:**
Router should route request `GET /api/v1/orders ` to correct handler 

**Actual result:**
Router return `Not Found` for request `GET /api/v1/orders `

Works well if the prefix contains only one path fragment:

`val routes = Router("/api/" -> ordersRoutes)`

**Http4s version**: `1.0.0-M4`

### PR DESCRIPTION
**Pull request by hamnis**
Added deprecations to indexOf and indexOfString and added the implementation to findSplit and findSplitOfString

Fixes #3713

### CODE REVIEW

**Review by ChristopherDavenport — APPROVED** [review]

File: server/src/test/scala/org/http4s/server/RouterSpec.scala [hunk 1]
```diff
@@ -51,13 +51,23 @@ class RouterSpec extends Http4sSpec with Http4sLegacyMatchersIO {
...
+      }
+    )
   )
 
   "A router" should {
     "translate mount prefixes" in {
       service.orNotFound(Request[IO](GET, uri"/numbers/1")) must returnBody("one")
       service.orNotFound(Request[IO](GET, uri"/numb/1")) must returnBody("two")
+      service.orNotFound(Request[IO](GET, uri"/numbers/v1/1")) must returnBody("Yeah")
+      service.orNotFound(Request[IO](GET, uri"/numbers/v2/1")) must returnBody("Indeed")
```
Comment (Daenyth) [inline server/src/test/scala/org/http4s/server/RouterSpec.scala:70]: 👍

**Review by Daenyth — APPROVED** [review]
